version: '3.4'
services:
  
  helmai:
    build:
      context: artificial-intelligence
      dockerfile: Dockerfile.AI
    ports:
      - "5001:5000"

  helmbe:
    build:
      context: back-end
      dockerfile: Dockerfile.BE
    ports:
      - "5000:5000"
    depends_on:
      - helmai

  helmfe:
    build:
      context: front-end
      dockerfile: Dockerfile.FE
    ports:
      - "3000:3000"
    depends_on:
      - helmbe
      - helmai