version: '3.4'
services:

  be-container:
    build:
      context: back-end
      dockerfile: Dockerfile.BE
    command: python app.py
    volumes:
      - "./back-end/:/home/backenduser/workdir"
    ports:
      - "5000:5000"
  
  ai-container:
    build:
      context: artificial-intelligence
      dockerfile: Dockerfile.AI
    command: python app.py
    volumes:
      - "./artificial-intelligence/:/home/aiuser/workdir"
    ports:
      - "5001:5000"

  fe-container:
    build:
      context: front-end
      dockerfile: Dockerfile.FE
    ports:
      - "3000:3000"
    depends_on:
      - be-container
      - ai-container